language: cpp
sudo: required
compiler: g++
os: linux
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake
install:
    - sudo apt-get -y install libpfm4-dev
before_script:
    - export CC=gcc && CXX=g++
    - mkdir build && cd build
    - cmake ../
script:
    - make
