language: cpp
sudo: required
compiler: g++
os: linux
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake
install:
    - sudo apt-get -y install libpfm4-dev
before_script:
    - export CC=gcc && CXX=g++
    - mkdir build && cd build
    - cmake ../
script:
    - make
before_deploy:
    - git config --local user.name "lebensterben"
    - git config --local user.email "lebensterben@users.noreply.github.com"
    - export TRAVIS_TAG=${$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
deploy:
    provider: releases
    api_key: "$GITHUB_TOKEN"
    file: 
        - "pqfastscan"
        - "pqsca"
    skip_cleanup: true
